# Generated by Django 5.2.10 on 2026-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('body', models.TextField()),
                ('video', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
