# Generated by Django 5.2.10 on 2026-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='body',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
