# Generated by Django 5.2.10 on 2026-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_body_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.CharField(default='Course'),
        ),
    ]
