# Generated by Django 5.2.10 on 2026-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(),
        ),
    ]
