# Generated by Django 5.2.10 on 2026-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_body_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
