# Generated by Django 5.2.10 on 2026-01-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='body',
        ),
    ]
