# Generated by Django 5.2.10 on 2026-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='teacher',
            new_name='isTeacher',
        ),
        migrations.AddField(
            model_name='myuser',
            name='enrollmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hireDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
