# Generated by Django 5.2.10 on 2026-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('file', models.CharField()),
                ('course', models.CharField(default='Course')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
